service: thanksforfeedback

provider:
  name: aws
  architecture: arm64
  deploymentMethod: direct
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, "production"}
  region: eu-west-2
  logRetentionInDays: 30
  apiGateway:
    description: "Thanks for the Feedback"
  environment:
    SENTRY_DSN: ${ssm:/serverless/${self:service}-${sls:stage}/SENTRY_DSN, ""}
    GOOGLE_SHEETS_CREDENTIALS: ${ssm:/serverless/${self:service}-${sls:stage}/GOOGLE_SHEETS_CREDENTIALS}

resources:
  Description: "Thanks for the Feedback"

functions:
  app:
    description: "Thanks for the Feedback - app"
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    image:
      uri: 253670703218.dkr.ecr.eu-west-2.amazonaws.com/${self:service}-${sls:stage}:latest
